apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: django-worker
  name: django-worker
  namespace: default
spec:
  minReadySeconds: 0
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: django-worker
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: django-worker
    spec:
      containers:
      - command:
        - sh
        - -c
        - celery worker -l info -A django -B -E
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              key: username
              name: cloudsql-db-credentials
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: cloudsql-db-credentials
        envFrom:
        - configMapRef:
            name: django-configmap
        image: gcr.io/$PROJECT_ID/django-worker:xxxxxxxx-prod
        imagePullPolicy: Always
        name: django-worker
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - command:
        - /cloud_sql_proxy
        - -instances=$PROJECT_ID:$REGION:django-db=tcp:5432
        - -credential_file=/secrets/cloudsql/credentials.json
        envFrom:
        - configMapRef:
            name: django-configmap
        image: gcr.io/cloudsql-docker/gce-proxy:1.11
        imagePullPolicy: IfNotPresent
        name: cloudsql-proxy
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /secrets/cloudsql
          name: cloudsql-instance-credentials
          readOnly: true
      - image: memcached
        imagePullPolicy: Always
        name: memcached
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 3
      volumes:
      - name: cloudsql-instance-credentials
        secret:
          defaultMode: 420
          secretName: cloudsql-instance-credentials
