apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: django-app
  name: django-app
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: django-app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
      - command:
        - sh
        - -c
        - python manage.py runserver 0.0.0.0:8000 --settings=django.settings.prod
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              key: username
              name: cloudsql-db-credentials
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: cloudsql-db-credentials
        envFrom:
        - configMapRef:
            name: django-django-configmap
        image: gcr.io/$PROJECT_ID/django-app:xxxxxxxx-prod
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 2
          httpGet:
            path: /
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 25
          periodSeconds: 30
          successThreshold: 2
          timeoutSeconds: 1
        name: django-app
        ports:
        - containerPort: 8000
          protocol: TCP
        readinessProbe:
          failureThreshold: 2
          httpGet:
            path: /
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 20
          successThreshold: 2
          timeoutSeconds: 1
        resources:
          requests:
            cpu: 600m
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /code/django/staticfiles
          name: nfs-pv
      - command:
        - /cloud_sql_proxy
        - -instances=$PROJECT_ID:$REGION:django-db=tcp:5432
        - -credential_file=/secrets/cloudsql/credentials.json
        envFrom:
        - configMapRef:
            name: django-configmap
        image: gcr.io/cloudsql-docker/gce-proxy:1.11
        imagePullPolicy: IfNotPresent
        name: cloudsql-proxy
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /secrets/cloudsql
          name: cloudsql-instance-credentials
          readOnly: true
      - image: memcached
        imagePullPolicy: Always
        name: memcached
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
      terminationGracePeriodSeconds: 3
      volumes:
      - name: cloudsql-instance-credentials
        secret:
          defaultMode: 420
          secretName: cloudsql-instance-credentials
      - name: nfs-pv
        persistentVolumeClaim:
          claimName: nfs-pvc
