apiVersion: v1
kind: Service
metadata:
  labels:
    app: django-app
  name: django-app-service
  namespace: default
spec:
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8000
  selector:
    app: django-app
  type: NodePort
