apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  namespace: default
spec:
  ports:
  - name: ampq1
    port: 5671
    protocol: TCP
    targetPort: 5671
  - name: ampq2
    port: 5672
    protocol: TCP
    targetPort: 5672
  selector:
    app: rabbitmq
